# Site settings
title: Personal Website
name: My Name
description: My personal website hosted on GitHub Pages
url: https://baba786.github.io

# Build settings
remote_theme: mmistakes/minimal-mistakes@4.24.0

# Minimal Mistakes settings
minimal_mistakes_skin: "default" # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Author
author:
  name: "Your Name"
  bio: "Web developer and tech enthusiast"
  location: "Your Location"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/baba786"

# Includes & Excludes
include:
  - _pages

# Front Matter Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:path/

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
